<a href="https://colab.research.google.com/github/baeseungyou/study/blob/main/13%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

In [1]:
from transformers import TFBertForMaskedLM

In [2]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased')

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFBertForMaskedLM.

All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


In [3]:
from transformers import AutoTokenizer

In [4]:
tokenizer = AutoTokenizer.from_pretrained("bert-large-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [5]:
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')

In [6]:
tokenizer.cls_token_id

101

In [7]:
tokenizer.sep_token_id

102

In [8]:
tokenizer.mask_token_id

103

In [9]:
inputs

{'input_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=
array([[ 101, 4715, 2003, 1037, 2428, 4569,  103, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 9), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [10]:
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [11]:
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [12]:
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


In [13]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer, device=0)

In [14]:
pip('Soccer is a really fun [MASK].')

[{'score': 0.7621108889579773,
  'token': 4368,
  'token_str': 'sport',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.20342084765434265,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.01220855675637722,
  'token': 2518,
  'token_str': 'thing',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.0018630273407325149,
  'token': 4023,
  'token_str': 'activity',
  'sequence': 'soccer is a really fun activity.'},
 {'score': 0.0013354882830753922,
  'token': 2492,
  'token_str': 'field',
  'sequence': 'soccer is a really fun field.'}]

In [15]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.25628945231437683,
  'token': 2265,
  'token_str': 'show',
  'sequence': 'the avengers is a really fun show.'},
 {'score': 0.17284151911735535,
  'token': 3185,
  'token_str': 'movie',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.11107683181762695,
  'token': 2466,
  'token_str': 'story',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.07248976081609726,
  'token': 2186,
  'token_str': 'series',
  'sequence': 'the avengers is a really fun series.'},
 {'score': 0.0704662948846817,
  'token': 2143,
  'token_str': 'film',
  'sequence': 'the avengers is a really fun film.'}]

In [16]:
pip('I went to [MASK] this morning.')

[{'score': 0.35730651021003723,
  'token': 2147,
  'token_str': 'work',
  'sequence': 'i went to work this morning.'},
 {'score': 0.23304501175880432,
  'token': 2793,
  'token_str': 'bed',
  'sequence': 'i went to bed this morning.'},
 {'score': 0.12845051288604736,
  'token': 2082,
  'token_str': 'school',
  'sequence': 'i went to school this morning.'},
 {'score': 0.06230581924319267,
  'token': 3637,
  'token_str': 'sleep',
  'sequence': 'i went to sleep this morning.'},
 {'score': 0.04695252329111099,
  'token': 2465,
  'token_str': 'class',
  'sequence': 'i went to class this morning.'}]

In [19]:
!pip install torch tensorflow transformers

In [23]:
# 필요한 라이브러리 임포트
import tensorflow as tf
from transformers import TFBertForMaskedLM, BertTokenizer

model_name = 'klue/bert-base'
model = TFBertForMaskedLM.from_pretrained(model_name, from_pt=True)
tokenizer = BertTokenizer.from_pretrained(model_name)

# 파이프라인 입력 문장
sentences = [
    "축구는 정말 재미있는[MASK]다.",
    "어벤져스는 정말 재미있는[MASK]다.",
    "나는 오늘 아침에[MASK]에 출근을 했다."
]

for sentence in sentences:
    # 입력 텍스트를 토큰화
    inputs = tokenizer(sentence, return_tensors='tf')

    outputs = model(inputs['input_ids'], attention_mask=inputs['attention_mask'])

    predictions = outputs.logits

    mask_token_index = tf.where(inputs['input_ids'] == tokenizer.mask_token_id)[0, 1]
    predicted_token_id = tf.argmax(predictions[0, mask_token_index]).numpy()
    predicted_token = tokenizer.decode(predicted_token_id)

    # 결과 출력
    print(f"입력 문장: {sentence}")
    print(f"예측된 단어: {predicted_token}\n")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForMaskedLM: ['bert.embeddings.position_ids', 'cls.predictions.decoder.bias']
- This IS expected if you are initializing TFBertForMaskedLM from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForMaskedLM from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertForMaskedLM were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


입력 문장: 축구는 정말 재미있는[MASK]다.
예측된 단어: 스포츠

입력 문장: 어벤져스는 정말 재미있는[MASK]다.
예측된 단어: 영화

입력 문장: 나는 오늘 아침에[MASK]에 출근을 했다.
예측된 단어: 회사

