<a href="https://colab.research.google.com/github/baeseungyou/study/blob/main/%ED%85%8D%EC%8A%A4%ED%8A%B8%EC%A0%95%EB%B3%B4%EC%B2%98%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install nltk

In [ ]:
import nltk
from nltk.tokenize import sent_tokenize

#샘플 텍스트
txt = "자연어 처리는 인공지능의 중요한 분야 중 하나입니다. 이는 인간의 언어를 이해하고 생성하는 기술입니다. 이 과정에는 다양한 알고리즘이 사용됩니다."

#nltk 데이터 다운로드 (최초 1회 필요)
nltk.download('punkt')

#문장 토큰화
sentences = sent_tokenize(txt) # Changed 'text' to 'txt'

#결과 출력
for i, sentence in enumerate(sentences, 1):
    print(f"문장 {i}: {sentence}")

문장 1: 자연어 처리는 인공지능의 중요한 분야 중 하나입니다.
문장 2: 이는 인간의 언어를 이해하고 생성하는 기술입니다.
문장 3: 이 과정에는 다양한 알고리즘이 사용됩니다.


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import nltk
from nltk.tokenize import word_tokenize

#샘플 텍스트
text = "자연어 처리는 인공지능의 중요한 분야입니다."

#nltk 데이터 다운로드 (최초 1회 필요)
nltk.download('punkt')

#단어 토큰화
words = word_tokenize(text)

#결과 출력
for i, word in enumerate(words, 1):
    print(f"단어 {i}: {word}")

단어 1: 자연어
단어 2: 처리는
단어 3: 인공지능의
단어 4: 중요한
단어 5: 분야입니다
단어 6: .


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
import re
from bs4 import BeautifulSoup

#샘플 텍스트
text = "<html>자연어 처리는 매우 중요합니다!!! 😊 #인공지능 </html>"

#1. HTML 태그 제거
def remove_html(text):
  soup = BeautifulSoup(text, "html.parser")
  return soup.get_text()

#2. 특수 문자 제거
def remove_special_characters(text):
  #알파벳, 한글, 숫자를 제외한 나머지 문자 제거
  return re.sub(r'[^a-zA-Z0-9가-힣\s]', '', text)

#3. 이모티콘 제거
def remove_emojis(text):
  emoji_pattern = re.compile("["
                        u"\0001F600-\U0001F64F" #이모티콘
                        u"\0001F300-\U0001F5FF" #기호 & 피토그래프
                        u"\0001F680-\U0001F6FF" # 교통 & 국기
                        u"\0001F1E0-\U0001F1FF" # 국기
                            "] + ", flags=re.UNICODE)
  return emoji_pattern.sub(r'', text)

In [ ]:
pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 44.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 23.0 MB/s eta 0:00:00


In [ ]:
pip install tensorflow

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

#샘플 문장들
sentences = [
    "나는 자연어 처리를 좋아합니다",
    "자연어 처리는 매우 재미있습니다",
    "나는 자연어 처리를 배우고 있습니다"
]

#Tokenizer 객체 생성
tokenizer = Tokenizer()

#단어 집합을 생성하고 각 단어에 고유한 숫자를 할당
tokenizer.fit_on_texts(sentences)

#텍스트를 정수 시퀀스로 변환
encoded_sentences = tokenizer.texts_to_sequences(sentences)

#단어 집합 출력
word_index = tokenizer.word_index
print("단어 집합:", word_index)

#정수 인코딩 결과 출력
print("정수 인코딩 결과:", encoded_sentences)

단어 집합: {'자연어': 1, '나는': 2, '처리를': 3, '좋아합니다': 4, '처리는': 5, '매우': 6, '재미있습니다': 7, '배우고': 8, '있습니다': 9}
정수 인코딩 결과: [[2, 1, 3, 4], [1, 5, 6, 7], [2, 1, 3, 8, 9]]


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

#샘플 문장들
sentences = [
    "나는 자연어 처리를 좋아합니다",
    "자연어 처리는 매우 재미있습니다",
    "나는 자연어 처리를 배우고 있습니다"
]

#Tokenizer 객체 생성 및 단어 집합 생성
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

#텍스트를 정수 시퀀스로 변환
encoded_sentences = tokenizer.texts_to_sequences(sentences)

#정수 인코딩 결과 출력
print("정수 인코딩 결과:", encoded_sentences)

#패딩 적용
padded_sentences = pad_sequences(encoded_sentences, padding='post')

#패딩 적용 결과 출력
print("패딩 적용 후 결과: ", padded_sentences)

정수 인코딩 결과: [[2, 1, 3, 4], [1, 5, 6, 7], [2, 1, 3, 8, 9]]
패딩 적용 후 결과:  [[2 1 3 4 0]
 [1 5 6 7 0]
 [2 1 3 8 9]]


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

#샘플 문장들
sentences = [
    "나는 자연어 처리를 좋아합니다",
    "자연어 처리는 매우 재미있습니다",
    "나는 자연어 처리를 배우고 있습니다"
]

# Tokenizer 객체 생성 및 단어 집합 생성
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

#텍스트를 정수 시퀀스로 변환
encoded_sentences = tokenizer.texts_to_sequences(sentences)

#단어 집합 출력
word_index = tokenizer.word_index
print("단어 집합:", word_index)

#정수 인코딩된 첫 번째 문장에 대한 원-핫 인코딩 적용
encoded_sentence = encoded_sentences[0]
one_hot_encoded = to_categorical(encoded_sentence, num_classes=len(word_index) + 1) #인덱스가 1부터 시작하므로

#원-핫 인코딩 결과 출력
print("정수 인코딩 결과:", encoded_sentence)
print("원-핫 인코딩 결과:\n", one_hot_encoded)

단어 집합: {'자연어': 1, '나는': 2, '처리를': 3, '좋아합니다': 4, '처리는': 5, '매우': 6, '재미있습니다': 7, '배우고': 8, '있습니다': 9}
정수 인코딩 결과: [2, 1, 3, 4]
원-핫 인코딩 결과:
 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [4]:
!pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 80.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 30.8 MB/s eta 0:00:00


In [10]:
import pandas as pd
from konlpy.tag import Okt
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

# 1. 파일 읽기
file_path = "C:/2주차_텍스트.csv"  # 파일 경로 수정: \를 /로 변경 또는 \\ 사용
data = pd.read_csv(file_path)

# 데이터 확인
print("파일 내용 확인:")
print(data.head())

# 텍스트 데이터 추출 (첫 번째 컬럼을 사용한다고 가정)
text_data = data.iloc[:, 0].dropna().tolist()  # 결측치 제거 후 리스트로 변환

# 2. 토큰화, 표제어 추출, 불용어 처리
okt = Okt()
stopwords = ['은', '는', '이', '가', '을', '를', '에', '의', '도', '으로', '그리고', '하지만']

# 각 문장을 토큰화하고 불용어를 제거한 결과를 저장할 리스트
tokenized_sentences = []
for sentence in text_data:
    # 형태소 분석 및 토큰화
    tokens = okt.morphs(sentence)
    # 불용어 제거
    tokens = [word for word in tokens if word not in stopwords]
    tokenized_sentences.append(tokens)

# 토큰화 결과 출력
print("\n토큰화 및 불용어 제거 결과:")
for idx, tokens in enumerate(tokenized_sentences):
    print(f"문장 {idx + 1}: {tokens}")

# 3. 정수 인코딩
tokenizer = Tokenizer()
tokenizer.fit_on_texts(tokenized_sentences)
encoded_sentences = tokenizer.texts_to_sequences(tokenized_sentences)

# 정수 인코딩 결과 출력
print("\n정수 인코딩 결과:")
for idx, encoded in enumerate(encoded_sentences):
    print(f"문장 {idx + 1}: {encoded}")

# 형태소-정수 매핑 정보 출력
print("\n형태소-정수 매핑 정보:")
print(tokenizer.word_index)

# 4. 패딩
max_length = max(len(sentence) for sentence in encoded_sentences)
padded_sentences = pad_sequences(encoded_sentences, maxlen=max_length, padding='post')

# 패딩 결과 출력
print("\n패딩 결과:")
for idx, padded in enumerate(padded_sentences):
    print(f"문장 {idx + 1}: {padded}")

# 5. 원-핫 인코딩 (첫 번째 문장만 처리)
first_sentence = encoded_sentences[0]
num_words = len(tokenizer.word_index) + 1
one_hot_encoding = np.eye(num_words)[first_sentence]

# 원-핫 인코딩 결과 출력
print("\n첫 번째 문장의 원-핫 인코딩 결과:")
print(one_hot_encoding)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/2주차_텍스트.csv'